apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-helm.fullname" . }}-config
  labels:
  {{- include "mysql-helm.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.configmap.mysqlDatabase | quote }}