apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-helm.fullname" . }}-secret
  labels:
  {{- include "mysql-helm.labels" . | nindent 4 }}
data:
  MYSQL_ROOT_PASSWORD: {{ required "secret.mysqlRootPassword is required" .Values.secret.mysqlRootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ required "secret.mysqlPassword is required" .Values.secret.mysqlPassword | b64enc | quote }}
  MYSQL_USER: {{ required "secret.mysqlUser is required" .Values.secret.mysqlUser | b64enc | quote }}
type: Opaque