apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wd-helm.fullname" . }}-config
  labels:
  {{- include "wd-helm.labels" . | nindent 4 }}
data:
  WORDPRESS_DATABASE_HOST: {{ .Values.configmap.wordpressDatabaseHost | quote }}
  WORDPRESS_DATABASE_NAME: {{ .Values.configmap.wordpressDatabaseName | quote }}
  MARIADB_PORT_NUMBER: {{ .Values.configmap.wordpressDatabasePort | quote }}
  WORDPRESS_USERNAME: {{ .Values.configmap.wordpressUsername | quote }}
