apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wd-helm.fullname" . }}-dep
  labels:
    {{- include "wd-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wd-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wd-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "wd-helm.fullname" . }}-pod
          image: "{{ .Values.image.repository }}"
          envFrom:
            - configMapRef:
                name: {{ include "wd-helm.fullname" . }}-config
            - secretRef:
                name: {{ include "wd-helm.fullname" . }}-secret
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "wd-helm.fullname" . }}-vol
              mountPath: {{ .Values.volumemounts.path }}
      volumes:
      - name: {{ include "wd-helm.fullname" . }}-vol
        persistentVolumeClaim:
          claimName: {{ include "wd-helm.fullname" . }}-pvc
