apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wd-helm.fullname" . }}-pvc
  labels:
  {{- include "wd-helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}