apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wd-helm.fullname" . }}-secret
  labels:
  {{- include "wd-helm.labels" . | nindent 4 }}
data:
  WORDPRESS_DATABASE_PASSWORD: {{ required "secret.wordpressDatabasePassword is required" .Values.secret.wordpressDatabasePassword | b64enc | quote }}
  WORDPRESS_DATABASE_USER: {{ required "secret.wordpressDatabaseUser is required" .Values.secret.wordpressDatabaseUser | b64enc | quote }}
  WORDPRESS_PASSWORD: {{ required "secret.wordpressDatabasePassword is required" .Values.secret.wordpressDatabasePassword | b64enc | quote }}
type: Opaque
